/** 与后端 constants/errorCodes 对齐的错误码镜像（前端用于提示映射） */
export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID: "AUTH_INVALID",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",

  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  TICKET_STATUS_CONFLICT: "TICKET_STATUS_CONFLICT",
  TICKET_ALREADY_DISPATCHED: "TICKET_ALREADY_DISPATCHED",
  TICKET_STATUS_FLOW_VIOLATION: "TICKET_STATUS_FLOW_VIOLATION",

  CREW_NOT_FOUND: "CREW_NOT_FOUND",
  CREW_OFF_DUTY: "CREW_OFF_DUTY",
  CREW_BUSY: "CREW_BUSY",
  CREW_SKILL_MISMATCH: "CREW_SKILL_MISMATCH",

  PART_NOT_FOUND: "PART_NOT_FOUND",
  PART_STOCK_INSUFFICIENT: "PART_STOCK_INSUFFICIENT",
  USAGE_NOT_FOUND: "USAGE_NOT_FOUND",
  USAGE_ALREADY_APPROVED: "USAGE_ALREADY_APPROVED",
  USAGE_NOT_PENDING: "USAGE_NOT_PENDING",

  FAULT_REPORT_NOT_FOUND: "FAULT_REPORT_NOT_FOUND",
  FAULT_ALREADY_CONVERTED: "FAULT_ALREADY_CONVERTED"
} as const;

/** 并发冲突类错误统一提示“请刷新” */
export const CONFLICT_CODES = new Set<string>([
  ERROR_CODES.TICKET_STATUS_CONFLICT,
  ERROR_CODES.TICKET_ALREADY_DISPATCHED,
  ERROR_CODES.CREW_BUSY,
  ERROR_CODES.USAGE_ALREADY_APPROVED,
  ERROR_CODES.USAGE_NOT_PENDING,
  ERROR_CODES.PART_STOCK_INSUFFICIENT
]);
