/** 与后端 constants/errorCodes.ts 对齐；前端用于提示与按钮禁用判断。 */
export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID: "AUTH_INVALID",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",

  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  CREW_NOT_ON_DUTY: "CREW_NOT_ON_DUTY",
  CREW_SKILL_MISMATCH: "CREW_SKILL_MISMATCH",
  CREW_BUSY: "CREW_BUSY",
  DISPATCH_CONFLICT: "DISPATCH_CONFLICT",

  TICKET_NOT_DISPATCHABLE: "TICKET_NOT_DISPATCHABLE",
  TICKET_INVALID_TRANSITION: "TICKET_INVALID_TRANSITION",
  TICKET_VERSION_CONFLICT: "TICKET_VERSION_CONFLICT",

  PART_NOT_FOUND: "PART_NOT_FOUND",
  PART_STOCK_INSUFFICIENT: "PART_STOCK_INSUFFICIENT",
  PART_ALREADY_APPROVED: "PART_ALREADY_APPROVED",
  PART_NOT_PENDING: "PART_NOT_PENDING",

  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
