export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID: "AUTH_INVALID",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",

  // ---- 抢修工单闭环错误码 ----
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  TICKET_STATUS_CONFLICT: "TICKET_STATUS_CONFLICT",
  TICKET_ALREADY_DISPATCHED: "TICKET_ALREADY_DISPATCHED",
  TICKET_STATUS_FLOW_VIOLATION: "TICKET_STATUS_FLOW_VIOLATION",

  CREW_NOT_FOUND: "CREW_NOT_FOUND",
  CREW_OFF_DUTY: "CREW_OFF_DUTY",
  CREW_BUSY: "CREW_BUSY",
  CREW_SKILL_MISMATCH: "CREW_SKILL_MISMATCH",

  PART_NOT_FOUND: "PART_NOT_FOUND",
  PART_STOCK_INSUFFICIENT: "PART_STOCK_INSUFFICIENT",
  USAGE_NOT_FOUND: "USAGE_NOT_FOUND",
  USAGE_ALREADY_APPROVED: "USAGE_ALREADY_APPROVED",
  USAGE_NOT_PENDING: "USAGE_NOT_PENDING",

  FAULT_REPORT_NOT_FOUND: "FAULT_REPORT_NOT_FOUND",
  FAULT_ALREADY_CONVERTED: "FAULT_ALREADY_CONVERTED"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
